name: Push dev shell to FlakeHub Cache

on:
  push:
    branches: [main]

jobs:
  push-dev-shell-to-flakehub-cache:
    env:
      ACTIONS_STEP_DEBUG: true
    runs-on: ${{ matrix.systems.runner }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        systems:
          - nix-system: aarch64-darwin
            runner: macos-latest-xlarge
          - nix-system: x86_64-linux
            runner: UbuntuLatest32Cores128G
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: DeterminateSystems/determinate-nix-action@d96678350ffd6a456235832eb11e1c491589b7bb # main
      - uses: DeterminateSystems/flakehub-cache-action@77c6bddd7d747943530aaa578c57f233ee5d920e # main
      - name: Build dev shell for ${{ matrix.systems.nix-system }} on ${{ matrix.systems.runner }}
        env:
          NIX_SYSTEM: ${{ matrix.systems.nix-system }}
        run: |
          nix build ".#devShells.${NIX_SYSTEM}.default"
